trigger:
  - main

pool:
  name: 'Default'

steps:

- checkout: self

- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '1.15.9'


- task: TerraformTask@5
  displayName: 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/preprod/'
    backendServiceArm: 'keraj_svc'
    backendAzureRmOverrideSubscriptionID: '83d4cba0-c6b0-4b71-8050-0b7fd5ba5202'
    backendAzureRmResourceGroupName: 'b18g35-common-rg'
    backendAzureRmStorageAccountName: 'b18g35storageaccount2'
    backendAzureRmContainerName: 'vkcontainer'
    backendAzureRmKey: 'vikasbhai.tfstate'

- task: TerraformTask@5
  displayName: 'Terraform validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/preprod/'

- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/preprod/'
    environmentServiceNameAzureRM: 'keraj_svc'
    environmentAzureRmOverrideSubscriptionID: '83d4cba0-c6b0-4b71-8050-0b7fd5ba5202'

- task: TerraformTask@5
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/preprod/'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'keraj_svc'
    environmentAzureRmOverrideSubscriptionID: '83d4cba0-c6b0-4b71-8050-0b7fd5ba5202'